#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
# 	   curl http://52.91.135.70/   --> returns string "Holberton School"
#	   curl http://52.91.135.70/   --> returns header info

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
